apiVersion: v1
kind: ConfigMap
metadata:
  name: evolution-api-env
  namespace: dev
data:
  AUTHENTICATION_API_KEY: w6wyAumFzpMuIkdWo1Mgpz5LWpN
  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES: "true"
  CACHE_LOCAL_ENABLED: "false"
  CACHE_REDIS_ENABLED: "true"
  CACHE_REDIS_PREFIX_KEY: evolution
  CACHE_REDIS_SAVE_INSTANCES: "true"
  CACHE_REDIS_TTL: "604800"
  CACHE_REDIS_URI: rediss://master.dev-cache.qblsji.use1.cache.amazonaws.com:6379/6
  CHATWOOT_BOT_CONTACT: "true"
  CHATWOOT_ENABLED: "false"
  CHATWOOT_IMPORT_DATABASE_CONNECTION_URI: postgresql://postgres:Maxxiio01@dev-evolution.cd0e04eoo7v3.us-east-1.rds.amazonaws.com:5432/chatwoot?sslmode=disable
  CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE: "true"
  CHATWOOT_MESSAGE_DELETE: "true"
  CHATWOOT_MESSAGE_READ: "true"
  CONFIG_SESSION_PHONE_CLIENT: Evolution API 2
  CONFIG_SESSION_PHONE_NAME: Chrome
  CONFIG_SESSION_PHONE_VERSION: 2.3000.1023204200
  CORS_CREDENTIALS: "true"
  CORS_METHODS: GET,POST,PUT,DELETE
  CORS_ORIGIN: '*'
  DATABASE_CONNECTION_CLIENT_NAME: evolution_exchange
  DATABASE_CONNECTION_URI: postgresql://postgres:Maxxiio01@dev-evolution.cd0e04eoo7v3.us-east-1.rds.amazonaws.com:5432/evolution?schema=public
  DATABASE_DELETE_MESSAGE: "true"
  DATABASE_PROVIDER: postgresql
  DATABASE_SAVE_DATA_CHATS: "true"
  DATABASE_SAVE_DATA_CONTACTS: "true"
  DATABASE_SAVE_DATA_HISTORIC: "true"
  DATABASE_SAVE_DATA_INSTANCE: "true"
  DATABASE_SAVE_DATA_LABELS: "true"
  DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
  DATABASE_SAVE_IS_ON_WHATSAPP_DAYS: "7"
  DATABASE_SAVE_IS_ON_WHATSAPP: "true"
  DATABASE_SAVE_MESSAGE_UPDATE: "true"
  DEL_INSTANCE: "false"
  DIFY_ENABLED: "false"
  EVENT_EMITTER_MAX_LISTENERS: "50"
  LANGUAGE: en
  LOG_BAILEYS: error
  LOG_COLOR: "true"
  LOG_LEVEL: ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET
  OPENAI_ENABLED: "false"
  PUSHER_ENABLED: "false"
  PUSHER_EVENTS_APPLICATION_STARTUP: "true"
  PUSHER_EVENTS_CALL: "true"
  PUSHER_EVENTS_CHATS_DELETE: "true"
  PUSHER_EVENTS_CHATS_SET: "true"
  PUSHER_EVENTS_CHATS_UPDATE: "true"
  PUSHER_EVENTS_CHATS_UPSERT: "true"
  PUSHER_EVENTS_CONNECTION_UPDATE: "true"
  PUSHER_EVENTS_CONTACTS_SET: "true"
  PUSHER_EVENTS_CONTACTS_UPDATE: "true"
  PUSHER_EVENTS_CONTACTS_UPSERT: "true"
  PUSHER_EVENTS_GROUP_PARTICIPANTS_UPDATE: "true"
  PUSHER_EVENTS_GROUPS_UPDATE: "true"
  PUSHER_EVENTS_GROUPS_UPSERT: "true"
  PUSHER_EVENTS_LABELS_ASSOCIATION: "true"
  PUSHER_EVENTS_LABELS_EDIT: "true"
  PUSHER_EVENTS_MESSAGES_DELETE: "true"
  PUSHER_EVENTS_MESSAGES_EDITED: "true"
  PUSHER_EVENTS_MESSAGES_SET: "true"
  PUSHER_EVENTS_MESSAGES_UPDATE: "true"
  PUSHER_EVENTS_MESSAGES_UPSERT: "true"
  PUSHER_EVENTS_PRESENCE_UPDATE: "true"
  PUSHER_EVENTS_QRCODE_UPDATED: "true"
  PUSHER_EVENTS_SEND_MESSAGE: "true"
  PUSHER_EVENTS_TYPEBOT_CHANGE_STATUS: "false"
  PUSHER_EVENTS_TYPEBOT_START: "false"
  PUSHER_GLOBAL_APP_ID: ""
  PUSHER_GLOBAL_CLUSTER: ""
  PUSHER_GLOBAL_ENABLED: "false"
  PUSHER_GLOBAL_KEY: ""
  PUSHER_GLOBAL_SECRET: ""
  PUSHER_GLOBAL_USE_TLS: "true"
  QRCODE_COLOR: '''#175197'''
  QRCODE_LIMIT: "30"
  RABBITMQ_ENABLED: "false"
  RABBITMQ_EVENTS_APPLICATION_STARTUP: "false"
  RABBITMQ_EVENTS_CALL: "false"
  RABBITMQ_EVENTS_CHATS_DELETE: "false"
  RABBITMQ_EVENTS_CHATS_SET: "false"
  RABBITMQ_EVENTS_CHATS_UPDATE: "false"
  RABBITMQ_EVENTS_CHATS_UPSERT: "false"
  RABBITMQ_EVENTS_CONNECTION_UPDATE: "false"
  RABBITMQ_EVENTS_CONTACTS_SET: "false"
  RABBITMQ_EVENTS_CONTACTS_UPDATE: "false"
  RABBITMQ_EVENTS_CONTACTS_UPSERT: "false"
  RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE: "false"
  RABBITMQ_EVENTS_GROUP_UPDATE: "false"
  RABBITMQ_EVENTS_GROUPS_UPSERT: "false"
  RABBITMQ_EVENTS_INSTANCE_CREATE: "false"
  RABBITMQ_EVENTS_INSTANCE_DELETE: "false"
  RABBITMQ_EVENTS_LOGOUT_INSTANCE: "false"
  RABBITMQ_EVENTS_MESSAGES_DELETE: "false"
  RABBITMQ_EVENTS_MESSAGES_EDITED: "false"
  RABBITMQ_EVENTS_MESSAGES_SET: "false"
  RABBITMQ_EVENTS_MESSAGES_UPDATE: "false"
  RABBITMQ_EVENTS_MESSAGES_UPSERT: "false"
  RABBITMQ_EVENTS_PRESENCE_UPDATE: "false"
  RABBITMQ_EVENTS_QRCODE_UPDATED: "false"
  RABBITMQ_EVENTS_REMOVE_INSTANCE: "false"
  RABBITMQ_EVENTS_SEND_MESSAGE: "false"
  RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS: "false"
  RABBITMQ_EVENTS_TYPEBOT_START: "false"
  RABBITMQ_EXCHANGE_NAME: evolution
  RABBITMQ_GLOBAL_ENABLED: "false"
  RABBITMQ_PREFIX_KEY: evolution
  RABBITMQ_URI: amqp://localhost
  S3_ACCESS_KEY: ""
  S3_BUCKET: evolution
  S3_ENABLED: "false"
  S3_ENDPOINT: s3.domain.com
  S3_PORT: "443"
  S3_REGION: eu-west-3
  S3_SECRET_KEY: ""
  S3_USE_SSL: "true"
  SENTRY_DSN: ""
  SERVER_PORT: "8899"
  SERVER_TYPE: http
  SERVER_URL: http://localhost:8899
  SQS_ACCESS_KEY_ID: ""
  SQS_ACCOUNT_ID: ""
  SQS_ENABLED: "false"
  SQS_REGION: ""
  SQS_SECRET_ACCESS_KEY: ""
  TYPEBOT_API_VERSION: latest
  TYPEBOT_ENABLED: "false"
  WA_BUSINESS_LANGUAGE: en_US
  WA_BUSINESS_TOKEN_WEBHOOK: evolution
  WA_BUSINESS_URL: https://graph.facebook.com
  WA_BUSINESS_VERSION: v20.0
  WEBHOOK_EVENTS_APPLICATION_STARTUP: "false"
  WEBHOOK_EVENTS_CALL: "true"
  WEBHOOK_EVENTS_CHATS_DELETE: "true"
  WEBHOOK_EVENTS_CHATS_SET: "true"
  WEBHOOK_EVENTS_CHATS_UPDATE: "true"
  WEBHOOK_EVENTS_CHATS_UPSERT: "true"
  WEBHOOK_EVENTS_CONNECTION_UPDATE: "true"
  WEBHOOK_EVENTS_CONTACTS_SET: "true"
  WEBHOOK_EVENTS_CONTACTS_UPDATE: "true"
  WEBHOOK_EVENTS_CONTACTS_UPSERT: "true"
  WEBHOOK_EVENTS_ERRORS_WEBHOOK: ""
  WEBHOOK_EVENTS_ERRORS: "false"
  WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE: "true"
  WEBHOOK_EVENTS_GROUPS_UPDATE: "true"
  WEBHOOK_EVENTS_GROUPS_UPSERT: "true"
  WEBHOOK_EVENTS_LABELS_ASSOCIATION: "true"
  WEBHOOK_EVENTS_LABELS_EDIT: "true"
  WEBHOOK_EVENTS_LOGOUT_INSTANCE: "false"
  WEBHOOK_EVENTS_MESSAGES_DELETE: "true"
  WEBHOOK_EVENTS_MESSAGES_EDITED: "true"
  WEBHOOK_EVENTS_MESSAGES_SET: "true"
  WEBHOOK_EVENTS_MESSAGES_UPDATE: "true"
  WEBHOOK_EVENTS_MESSAGES_UPSERT: "true"
  WEBHOOK_EVENTS_PRESENCE_UPDATE: "true"
  WEBHOOK_EVENTS_QRCODE_UPDATED: "true"
  WEBHOOK_EVENTS_REMOVE_INSTANCE: "false"
  WEBHOOK_EVENTS_SEND_MESSAGE: "true"
  WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS: "false"
  WEBHOOK_EVENTS_TYPEBOT_START: "false"
  WEBHOOK_GLOBAL_ENABLED: "false"
  WEBHOOK_GLOBAL_URL: ''''''
  WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: "false"
  WEBSOCKET_ENABLED: "false"
  WEBSOCKET_GLOBAL_EVENTS: "false"