apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: evolution-api
  name: evolution-api-deployment
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: evolution-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: evolution-api
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: master.dev-cache.qblsji.use1.cache.amazonaws.com
        - name: REDIS_PORT
          value: "6379"
        - name: POSTGRES_HOST
          value: dev-evolution.cd0e04eoo7v3.us-east-1.rds.amazonaws.com
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: Maxxiio01
        - name: POSTGRES_DB
          value: postgres
        envFrom:
        - configMapRef:
            name: evolution-api-env
        image: atendai/evolution-api:v2.2.3
        imagePullPolicy: Always
        name: evolution-api
        ports:
        - containerPort: 8899
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /evolution/instances
          name: evolution-instances
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: evolution-instances