services:
 api:
   container_name: evolution_api
   image: atendai/evolution-api:latest
   restart: always
   depends_on:
     - redis
     - postgres
   ports:
     - 8599:8599
   volumes:
     #- evolution_instances:/evolution/instances
     - /storage-db/evolution/instances:/evolution/instances
   networks:
     - evolution-net
   env_file:
     - .env
   expose:
     - 8599
 redis:
   image: redis:latest
   networks:
     - evolution-net
   container_name: redis
   command: >
     redis-server --port 6379 --appendonly yes
   volumes:
     #- evolution_redis:/data
     - /storage-db/evolution/evolution_redis:/data
   ports:
     - 6379:6379
 postgres:
   container_name: postgres
   image: postgres:15
   networks:
     - evolution-net
   command: [ "postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*" ]
   restart: always
   ports:
     - 5432:5432
   environment:
     - POSTGRES_USER=minerion
     - POSTGRES_PASSWORD=MiNerion342
     - POSTGRES_DB=evolution
     - POSTGRES_HOST_AUTH_METHOD=trust
   volumes:
     #- postgres_data:/var/lib/postgresql/data
     - /storage-db/evolution/postgres_data:/var/lib/postgresql/data
   expose:
     - 5432
#volumes:
# evolution_instances:
# evolution_redis:
# postgres_data:

networks:
 evolution-net:
   name: evolution-net
   driver: bridge
