apiVersion: v1
kind: Service
metadata:
  labels:
    app: evolution-api
  name: evolution-api-service
  namespace: qa
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8899
    protocol: TCP
    targetPort: 8899
  selector:
    app: evolution-api
  type: ClusterIP